apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: netmax
    count: 3

patches:
  - target:
      kind: Service
      name: netmax-svc
      
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 3000
      
