FROM node:20-alpine AS build 
WORKDIR /src  
COPY package.json package.json 
RUN npm install  
COPY . .
RUN npm run build 

FROM node:20-alpine 
COPY --from=build /src/dist/ /dist
EXPOSE 3000 
RUN npm install -g serve 
CMD [ "serve","-u","/dist" ]