kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: "C:/Users/prani/OneDrive/Desktop/LEARN REACT/crud-using-react-golang-and-postgres/backup/data"
        containerPath: /home/data
