apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmax
  namespace: netmax
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels: 
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - image: pranit007/netmax
        name: netmax
        ports:
        - containerPort: 3000
