FROM golang:1.23.2 AS build
WORKDIR /src 
COPY go.mod go.mod
RUN go mod download 
COPY . .  
RUN CGO_ENABLED=0 go build -o app . 
FROM scratch 
COPY --from=build /src/app /app 
EXPOSE 4000
CMD [ "/app" ]